name: Deploy no Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Dependências
        run: npm install
      - name: Deploy no Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes